kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: install-instantclient
  image: quay.io/tike/drone-install-instantclient:12.2
- name: test-init
  image: busybox
  commands:
  - chmod -R o+w /drone/src  
- name: test
  image: node:12
  user: node
  commands:
    - export OCI_LIB_DIR=$PWD/instantclient
    - export OCI_INC_DIR=$PWD/instantclient/sdk/include
    - npm install
# Refactor needed first
#    - npm test
    - npm run lint    
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/tike/melinda-oai-pmh-provider
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
image_pull_secrets:
- pull_docker_config
---
kind: secret
name: docker_username
data: BAQ6GAhFcEzRH6YclwjhnKCXevpiFc0hbL9RCYxV0FFaWqH9x4ap28XYRPNzy46Jv6ZKv/T5MkpYbszIhwMo6w==
---
kind: secret
name: docker_password
data: zaCML0PJjkMm4qyGTpTdnhPlQhsZfotPYJw4U87irNjPPBwh4KxRv22Nwcf5WMhW3lZzx8U98l+HYKHlrC41xl6KHnifi8mDeJ0AdhTRtf0MWsMsouyyI8UMO98=
---
kind: secret
name: pull_docker_config
data: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkR2xyWlN0cllXNXpZV3hzYVhOcmFYSnFZWE4wYjE5a2NtOXVaVjl0Wld4cGJtUmhPa1JRTUZkYVFWRXdXRTFRVFZoT05qaERRa0pRUmtoUlMwVktUbHBUVUVoTlRrOU9XRmRHVTBJMFZqTTROMDVVVmpWT1ZqWTRTakUxVUZoVlFWTldVRk09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
